#!/bin/bash
exec s6-setuidgid hatchpod \
    s6-env HOME=/home/hatchpod \
    s6-env HOST=0.0.0.0 \
    s6-env BROWSE_ROOT=/home/hatchpod/workspace \
    s6-env DEFAULT_CWD=/home/hatchpod/workspace \
    node /opt/api-server/dist/index.js
